fieldLayouts:
  95b66899-7137-40d8-93c6-09fad44f7afd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d61dfa5-75bd-456f-8990-639dfacf11a3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 41cd9aab-125e-4861-8818-00f3bfff43c8 # Lead Sheet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b693040-3ae4-4439-a202-d3070581f17e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59bcd338-8afd-4b98-b904-41bc93d58557 # Notation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1d8d59b-997a-4ed1-868c-f95b9b59cf98
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4782e046-95cd-4e3f-8eb0-cab1e0c072c4
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9d53bdc7-ff3a-40e4-b9ed-3f179981fdf7 # Songs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
