fieldLayouts:
  adef4dee-c043-4519-8ef5-284bdf828047:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 961199d9-8060-459d-936d-374cc5c98d43
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: c0556e53-47a9-489d-959e-4d7fa3e14cfa # Private
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2dc3f5c-617b-4c01-97ae-1e6b98dbbed3
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 5a2995c6-a302-45f5-b8e4-d1298ebe3775
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: e9724a2b-08e5-4af5-912f-8b72f34e4dd2 # Playlists
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
