fieldLayouts:
  adef4dee-c043-4519-8ef5-284bdf828047:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 961199d9-8060-459d-936d-374cc5c98d43
            warning: null
            width: 75
          -
            fieldUid: c0556e53-47a9-489d-959e-4d7fa3e14cfa # Private
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2dc3f5c-617b-4c01-97ae-1e6b98dbbed3
            warning: null
            width: 25
          -
            fieldUid: 1caa60b2-69ef-4633-a42b-1eddb1e8aa51
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9206a3d3-c057-467a-a1f2-738ae91cbbb6
            warning: null
            width: 100
        name: Content
        uid: 5a2995c6-a302-45f5-b8e4-d1298ebe3775
handle: default
hasTitleField: true
name: Default
section: e9724a2b-08e5-4af5-912f-8b72f34e4dd2 # Playlists
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
