defaultPlacement: end
fieldLayouts:
  f616c66f-bdbf-493b-b5ef-c5a538fcbaaf:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: artists
name: Artists
siteSettings:
  7926d1d4-2868-4570-a130-3ad5f97521f3: # TES
    hasUrls: true
    template: null
    uriFormat: 'artists/{slug}'
structure:
  maxLevels: 1
  uid: b8c4777f-fe24-4c99-9407-dd22e51aa2b7
