fieldLayouts:
  c64d785c-d424-4e9d-b55f-17d7aba15a8f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4607f7b4-70c5-4f40-a99c-ddc699d3df1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c7b3c740-8eae-4e72-81c8-bbb9ee7a7a3b
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _image-transforms
