columnSuffix: null
contentColumnType: string
fieldGroup: 645c0bbb-e71d-45b5-9df2-4f0857590a7a # Library
handle: categories
instructions: null
name: Categories
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add Category'
  showSiteMenu: true
  source: 'group:2475be09-4d11-4c7f-87f7-809d12c934e0' # Library
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
