columnSuffix: null
contentColumnType: string
fieldGroup: 645c0bbb-e71d-45b5-9df2-4f0857590a7a # Library
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
