currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: assets
layout: cc535655-d27d-44b9-bb0c-2a8c6b54fb85 # Default
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: null
prevParent: null
prevUrl: assets
sortOrder: 3
subnavBehaviour: null
type: craft
url: assets
