currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: tags
layout: cc535655-d27d-44b9-bb0c-2a8c6b54fb85 # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: null
prevParent: null
prevUrl: categories
sortOrder: 2
subnavBehaviour: null
type: craft
url: categories
