currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: cc535655-d27d-44b9-bb0c-2a8c6b54fb85 # Default
level: 1
newWindow: false
parent: null
prevLabel: Globals
prevLevel: 1
prevParent: null
prevUrl: globals
sortOrder: 5
subnavBehaviour: null
type: craft
url: globals
