currLabel: GraphQL
customIcon: ''
enabled: '1'
handle: graphql
icon: '@appicons/graphql.svg'
layout: cc535655-d27d-44b9-bb0c-2a8c6b54fb85 # Default
level: 1
newWindow: '0'
parentId: null
prevLabel: GraphQL
prevLevel: null
prevParentId: null
prevUrl: graphql
sortOrder: 8
type: craft
url: graphql
