currLabel: Users
customIcon: null
enabled: true
handle: users
icon: users
layout: cc535655-d27d-44b9-bb0c-2a8c6b54fb85 # Default
level: 1
newWindow: false
parent: null
prevLabel: Users
prevLevel: null
prevParent: null
prevUrl: users
sortOrder: 4
subnavBehaviour: null
type: craft
url: users
