currLabel: Webhooks
customIcon: null
enabled: true
handle: webhooks
icon: /Users/andy/Dev/tes-craft/vendor/craftcms/webhooks/src/icon-mask.svg
layout: cc535655-d27d-44b9-bb0c-2a8c6b54fb85 # Default
level: 1
newWindow: false
parent: null
prevLabel: Webhooks
prevLevel: 1
prevParent: null
prevUrl: webhooks
sortOrder: 10
subnavBehaviour: null
type: plugin
url: webhooks
